version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=ELASTIC
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data:rw
    networks:
      - honeynet
    ports:
      - 9200:9200
  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-container:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - honeynet
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
volumes:
  elasticsearchdata:
    driver: local
networks:
  honeynet:
    driver: bridge
